---
name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Link
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm --entrypoint "python3 manage.py test" app
      - name: Link
        run: docker-compose run --rm app sh -c "flake8"